###
POST http://localhost:8081/api/auth/signup
Content-Type: application/json

{
  "username": "test2",
  "email": "test2@yandex.ru",
  "phoneNumber": "+79002311313",
  "password": "password"
}

###
POST http://localhost:8081/api/auth/signin
Content-Type: application/json

{
  "username": "test2",
  "password": "password"
}