###

PUT localhost:8080/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZTMiLCJpYXQiOjE2OTU4NDMwOTgsImV4cCI6MTY5NTkyOTQ5OH0.nhsPlsgDeoC2dhtoAjsa-t876rPo1WtDTyR6BmHB_J0
Content-Type: application/json

{
  "id": "2",
  "status": "COOKING"
}

###

PUT localhost:8080/orders/courier
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZTMiLCJpYXQiOjE2OTU4NDMwOTgsImV4cCI6MTY5NTkyOTQ5OH0.nhsPlsgDeoC2dhtoAjsa-t876rPo1WtDTyR6BmHB_J0
Content-Type: application/json

{
  "id": "1",
  "courierId": "1"
}

###

GET localhost:8081/orders/awaiting-delivery
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjk2ODI4MjY5LCJleHAiOjE2OTY5MTQ2Njl9.KoCgIXMYWTsmCv7nd3bbFOWiUkbJrEa1ltoCgSSHJ8c

###
GET localhost:8080/orders/2

###
GET localhost:8080/orders/courier/1
