###

PUT localhost:8080/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZTMiLCJpYXQiOjE2OTU4NDMwOTgsImV4cCI6MTY5NTkyOTQ5OH0.nhsPlsgDeoC2dhtoAjsa-t876rPo1WtDTyR6BmHB_J0
Content-Type: application/json

{
  "id": "2",
  "status": "COOKING"
}

###

PUT localhost:8080/orders/courier
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZTMiLCJpYXQiOjE2OTU4NDMwOTgsImV4cCI6MTY5NTkyOTQ5OH0.nhsPlsgDeoC2dhtoAjsa-t876rPo1WtDTyR6BmHB_J0
Content-Type: application/json

{
  "id": "1",
  "courierId": "1"
}

###

GET http://localhost:8081/orders/awaiting-delivery?page=0
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjk3Mzc5NjM5LCJleHAiOjE2OTc0NjYwMzl9.PuLhC1xBASa_SJiHa5waoab0KcAWZecN-_ovVmHW1XM

###

GET http://localhost:8081/orders/delivering
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjk3Mzc5NjM5LCJleHAiOjE2OTc0NjYwMzl9.PuLhC1xBASa_SJiHa5waoab0KcAWZecN-_ovVmHW1XM

###
GET http://localhost:8081/orders/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZTMiLCJpYXQiOjE2OTU4NDMwOTgsImV4cCI6MTY5NTkyOTQ5OH0.nhsPlsgDeoC2dhtoAjsa-t876rPo1WtDTyR6BmHB_J0

###
GET localhost:8080/orders/courier/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZTMiLCJpYXQiOjE2OTU4NDMwOTgsImV4cCI6MTY5NTkyOTQ5OH0.nhsPlsgDeoC2dhtoAjsa-t876rPo1WtDTyR6BmHB_J0
