POST http://localhost:8080/shifts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MyIsImlhdCI6MTY5NTgyNTE2NywiZXhwIjoxNjk1OTExNTY3fQ.ZfGdhA1i3JYE4ESJ1UudkIM51AEcV3bTV41MRgqYURg

###
PUT http://localhost:8080/shifts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MyIsImlhdCI6MTY5NTgyNTE2NywiZXhwIjoxNjk1OTExNTY3fQ.ZfGdhA1i3JYE4ESJ1UudkIM51AEcV3bTV41MRgqYURg
Content-Type: application/json

{
  "id_shift": 1,
  "begin_shift" : "2023-09-27 16:03:51",
  "end_shift": "2023-09-27 16:03:51",
  "user_id": 1
}

###
DELETE http://localhost:8080/shifts/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MyIsImlhdCI6MTY5NTgyNTE2NywiZXhwIjoxNjk1OTExNTY3fQ.ZfGdhA1i3JYE4ESJ1UudkIM51AEcV3bTV41MRgqYURg

###
GET http://localhost:8080/shifts/courier/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MyIsImlhdCI6MTY5NTgyNTE2NywiZXhwIjoxNjk1OTExNTY3fQ.ZfGdhA1i3JYE4ESJ1UudkIM51AEcV3bTV41MRgqYURg
